config/routes.rb
Rails.application.routes.draw do
  
  resources :projects do
    resources :tasks
  end
  
  resources :users do
    resources :projects
    resources :tasks
  end

  resources :static_pages do
    put :sort, on: :collection
  end

  root to: "static_pages#index"
  match 'index', to: 'static_pages#index', via: [:get, :post]

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'

  #match '/delete_comment', to: 'tasks#destroy', via: 'delete'
  get '/projects/:project_id/tasks/:id(.:format)', to: 'tasks#destroy', as: 'delete_comment', via: 'delete'
  get '/users/:user_id/projects/:id(.:format)', to: 'projects#destroy', as: 'delete_project', via: 'delete'



  match 'auth/:provider/callback', to: 'sessions#fb_create',     via: 'get'
  match 'auth/failure', to: redirect('/'),                       via: 'get'
  match 'signout_fb', to: 'sessions#fb_destroy',                 via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates :name, presence: true
  default_scope { order("priority ASC") }

  def deadline_string
    deadline
  end

  def deadline_string=(deadline_str)
    self.deadline = Time.parse(deadline_str)
  rescue ArgumentError
    @deadline_invalid = true
  end

  def validate
    errors.add(:deadline, "is invalid") if @deadline_invalid
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authorized, except: [:index, :new]
  before_action :correct_user_tasks#, :except => [:edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    #@tasks = Task.all
    #@tasks = Task.where(project_id: project_id)
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @project = Project.find(params[:project_id])
    if current_user == @project.user
      @tasks.user_id = current_user.id
    else
      redirect_to root_path, notice: 'You can\'t create task for this project.'
    end
  end

  # GET /tasks/1/edit
  def edit
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks.build(task_params)
    @tasks.user_id = current_user.id
    @users = User.all
    @projects = Project.all

    respond_to do |format|
      if @tasks.save
        format.js
        format.html { redirect_to root_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.js
        format.html { redirect_to root_path, notice: 'There was a problem.' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.js
        format.html { redirect_to root_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.js
        format.html { redirect_to root_path, notice: 'There was a problem.' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to root_path, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.fetch(:task, {}).permit(:name, :priority, :status, :deadline, :project_id, :user_id, :comment)
    end

    def correct_user_tasks
      if current_user && @task
        unless @task.user == current_user
          redirect_to root_path, notice: 'You can\'t change task for this project.'
        end
      end
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_create_task_error.html.erb
<li class="new_task pr<%= project.id %> item alert alert-danger" name="pr<%= project.id %>" role="alert" >
  <p>You can't create task for another user!</p>
</li>

app/views/tasks/_done_task.html.erb
<%= form_for([project, task], remote: true) do |f| %>
  <div id="done_task_task<%= task.id %>">
    <div class="field status">
      <%= f.check_box :status, :onclick => "$('form#edit_task_#{task.id}').submit();", 'placeholder' => :status, size: 10 %>
    </div>
  </div>
<% end %>

app/views/tasks/_ed_form.html.erb
<li class="edit_task list-group-item item" draggable="false" >
  <%= form_for([project, task], remote: true) do |f| %>
    <div class="row">
      <div class="field col-md-1 col-xs-4 status">
        <%= f.check_box :status, 'placeholder' => :status, size: 10 %>
      </div>

      <div class="field col-md-3 col-xs-4">
        <%= f.text_field :name, id: :task_name, required: true, 'placeholder' => :task_name, size: 10 %>
      </div>

      <div class="field col-md-2 col-xs-4">
        <%= f.number_field :priority, id: :task_priority, 'placeholder' => :task_priority, min: 0 , max: 50 %>
      </div>

      <div class="field col-md-6 col-xs-12">
        <div class='input-group date datetimepicker1'>
            <input type='text' class="form-control" id="task_deadline" name="task[deadline]" style="display: none" />
            <%= f.text_field :deadline, id: :deadline, class: 'form-control', 'placeholder' => :deadline %>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="field col-md-8 col-xs-8">
        <%= f.text_field :comment, 'placeholder' => :comment, size: 50 %>
      </div>
      <div class="field col-md-2 col-xs-2">
        <%= link_to '', '#', class: 'back glyphicon glyphicon-floppy-remove', 'aria-hidden' => true, 'title' => 'back to task' %>
      </div>
      <div class="actions col-md-2 col-xs-2">
        <%= button_tag "", type: 'submit', class: "glyphicon glyphicon-floppy-saved", 'aria-hidden' => true, 'title' => 'save changes' %>
      </div>
    </div>
  <% end %>
</li>

app/views/tasks/_form.html.erb
<li class="new_task pr<%= project.id %> list-group-item item" name="pr<%= project.id %>">
  <%= form_for([project, @task], remote: true) do |f| %>
    <div class="row">
      <div class="field col-md-1 col-xs-4 status">
        <%= f.check_box :status, 'placeholder' => :status, size: 10 %>
      </div>

      <div class="field col-md-3 col-xs-4">
        <%= f.text_field :name, id: :task_name, required: true, 'placeholder' => :task_name, size: 10 %>
      </div>

      <div class="field col-md-2 col-xs-4">
        <%= f.number_field :priority, id: :task_priority, 'placeholder' => :task_priority, min: 0 , max: 0 %>
      </div>

      <div class="field col-md-6 col-xs-12">
        <div class='input-group date datetimepicker1'>
            <input type='text' class="form-control" id="task_deadline" name="task[deadline]" style="display: none" />
            <%= f.text_field :deadline, id: :deadline, class: 'form-control', 'placeholder' => :deadline %>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="field col-md-10 col-xs-10">
        <%= f.text_field :comment, 'placeholder' => :comment, size: 50 %>
      </div>
      <div class="actions col-md-2 col-xs-2">
        <%= f.submit '+' %>
      </div>
    </div>
  <% end %>
</li>

app/views/tasks/_task.html.erb
<li class="list-group-item item task 
  <% if current_user %>
    <% if current_user != task.user %>
      <%= 'disabled' %>
    <% end %>
  <% else %>
    <%= 'disabled' %>
  <% end %>" data-id="<%= task.id %>" data-toggle="popover" data-placement="right" data-content="<%= render partial: 'tasks/task_popover', locals: { task: task} %>" data-trigger="hover" id="task<%= task.id %>" data-html="true">
  <div class="row" data-toggle="popover" data-placement="right" data-content="<%= render partial: 'tasks/task_popover', locals: { task: task} %>" data-trigger="hover" data-html="true">
    
    <div class="col-md-2 col-xs-2">
      <% if current_user %>
        <% if current_user == task.user %>
          <%= render  partial: "tasks/done_task", locals: { task: task, project: task.project, 'draggable' => false } %>
        <% else %>
          <span class="glyphicon glyphicon-th-list" aria-hidden="true" title="sign in to have your own tasks"></span>
        <% end %>
      <% else %>
        <span class="glyphicon glyphicon-th-list" aria-hidden="true" title="sign in to have your own tasks"></span>
      <% end %>
    </div>
    <div class="col-md-2 col-xs-4">
      <% if task.status %>
        <del>
      <% end %>
      <%= task.name %>
      <% if task.status %>
        </del>
      <% end %>
    </div>
    <% if current_user %>
      <% if current_user == task.user %>
        <div class="col-md-4 s_devises"><%= if task.deadline then task.deadline.strftime('%d/%m/%Y %H:%M') end %></div>
        <div class="col-md-1 col-md-offset-1 col-xs-2"><%= link_to '', project_task_path(task.project, task), class: 'glyphicon glyphicon-search', 'aria-hidden' => true, 'title' => 'show task' %></div>
        <div class="col-md-1 col-xs-2"><%= link_to '', '#', class: 'ed_task glyphicon glyphicon-pencil', 'aria-hidden' => true, 'title' => 'edit task', remote: true %></div>
        <!-- edit_project_task_path(task.project, task) -->
        <div class="col-md-1 col-xs-2"><%= link_to '', delete_comment_path(task.project, task), method: :delete, remote: true, class: 'destroy_task glyphicon glyphicon-trash', 'aria-hidden' => true, 'title' => 'delete task' %></div>
        <!-- delete_comment_path(project, task) -->
      <% end %>
    <% end %>
  </div>
</li>

app/views/tasks/_task_popover.html.erb
<center><strong>Task&nbsp;:&nbsp;<%= task.name %></strong></center><br>
<small>Project:&nbsp;<%= task.project.name %></small><br>
<small>Owner&nbsp;:&nbsp;<%= task.user.first_name %>&nbsp;<%= task.user.last_name %></small>

<small>Status&nbsp;:&nbsp;<%= task.status %></small><br>
<small>Deadline&nbsp;:&nbsp;<%= task.deadline %></small><br>
<small>Priority&nbsp;:&nbsp;<%= task.priority %></small><br>
<small>Comment&nbsp;:&nbsp;<%= task.comment %></small><br>

<small>Created_at:&nbsp;<%= task.created_at %></small>

app/views/tasks/create.js.erb
$("<%= j(render 'task', task: @tasks) %>").insertBefore( ".new_task.pr<%= @tasks.project.id %>" )
$('#task<%= @tasks.id %>').hide()
$('#task<%= @tasks.id %>').show(1000)
$('.new_task').hide(1000)

app/views/tasks/destroy.js.erb
$('li#task<%= @task.id %>').hide(1000)

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', root_path %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Priority</th>
      <th>Status</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.priority %></td>
        <td><%= task.status %></td>
        <td><%= task.deadline %></td>
        <td><%= link_to 'Show', project_task_path(@project, task) %></td>
        <td><%= link_to 'Edit', edit_project_task_path(@project, task) %></td>
        <td><%= link_to 'Destroy', delete_comment_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_project_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/tasks/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<%= link_to 'Edit', edit_project_task_path(@task.project, @task) %> |
<%= link_to 'Back', root_path %>

app/views/tasks/update.js.erb
$('ul.list-group.pr<%= @task.project.id %>').replaceWith("<%= j(render  partial: 'projects/project', locals: { project: @task.project }) %>")
$('li.edit_task').hide()
$('.new_task').hide()
$('li.edit_task').attr("draggable", "false")
$('.new_task').attr("draggable", "false")
$('.task_each_div').attr("draggable", "true")