config/routes.rb
Rails.application.routes.draw do
  
  resources :projects do
    resources :tasks
  end
  
  resources :users do
    resources :projects
    resources :tasks
  end

  resources :static_pages do
    put :sort, on: :collection
  end

  root to: "static_pages#index"
  match 'index', to: 'static_pages#index', via: [:get, :post]

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'

  #match '/delete_comment', to: 'tasks#destroy', via: 'delete'
  get '/projects/:project_id/tasks/:id(.:format)', to: 'tasks#destroy', as: 'delete_comment', via: 'delete'
  get '/users/:user_id/projects/:id(.:format)', to: 'projects#destroy', as: 'delete_project', via: 'delete'



  match 'auth/:provider/callback', to: 'sessions#fb_create',     via: 'get'
  match 'auth/failure', to: redirect('/'),                       via: 'get'
  match 'signout_fb', to: 'sessions#fb_destroy',                 via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_header_clearfix.html.erb
<nav class="navbar-fixed-top">
  <ul class="nav nav-pills pull-right">
    <li role="presentation" class="active"><%= link_to "Main Page", root_path %></li>
    <li class="set_bg" role="presentation"><%= link_to "Users", users_path %></li>
    <li class="set_bg" role="presentation">
      <% if current_user %>
        <li class="set_bg" role="presentation"><%= link_to "#{current_user.first_name} #{current_user.last_name}", user_path(current_user) %></li>
        <li class="set_bg" role="presentation"><%= link_to "Sign Out", signout_path %></li>
        <li></li>
      <% else %>
        <!-- <li role="presentation"><%= link_to "Sign Up", signup_path %></li> -->
<!--         <li class="set_bg" role="presentation"><%= link_to "Sign in with Facebook", "/auth/facebook" %></li> -->
        <li class="set_bg" role="presentation"><%= link_to "Log In", signin_path %></li>
        <li class="set_bg" role="presentation"><%= link_to "Sign up", '#', id: 'add_user', class: "btn btn-lg btn-success" %></li>
      <% end %>
    </li>
  </ul>
</nav>
<h3 class="text-muted">To Do List</h3>