config/routes.rb
Rails.application.routes.draw do
  
  resources :projects do
    resources :tasks
  end
  
  resources :users do
    resources :projects
    resources :tasks
  end

  resources :static_pages do
    put :sort, on: :collection
  end

  root to: "static_pages#index"
  match 'index', to: 'static_pages#index', via: [:get, :post]

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get'

  #match '/delete_comment', to: 'tasks#destroy', via: 'delete'
  get '/projects/:project_id/tasks/:id(.:format)', to: 'tasks#destroy', as: 'delete_comment', via: 'delete'
  get '/users/:user_id/projects/:id(.:format)', to: 'projects#destroy', as: 'delete_project', via: 'delete'



  match 'auth/:provider/callback', to: 'sessions#fb_create',     via: 'get'
  match 'auth/failure', to: redirect('/'),                       via: 'get'
  match 'signout_fb', to: 'sessions#fb_destroy',                 via: 'get'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authorized, except: [:index]
  before_action :correct_user_projects# :only => [:edit, :update, :destroy]
  
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @projects = Project.all
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)
    @users = User.all
    @projects = Project.all
    @task = Task.new

    respond_to do |format|
      if @project.save
        format.js
        format.html { redirect_to root_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.js
        format.html { redirect_to root_path, notice: 'Project get errors.' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to root_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to root_path, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :user_id)
    end

    def correct_user_projects
      if current_user && @project
        unless @project.user == current_user
          redirect_to root_path, notice: 'You can\'t change this project.'
        end
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="new_project">  
  <%= form_with(model: @project, remote: true) do |form| %>
    <% if @project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :project_name, required: true %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/projects/_project.html.erb
<ul class="list-group pr<%= project.id %>", name="pr<%= project.id %>" >
  <li class="list-group-item list-group-item-info">
    <div class="row">
      <div class="col-md-3 col-xs-4"><strong><%= project.name %></strong></div>
      <div class="col-md-1 col-xs-1"><div><span class="glyphicon glyphicon-user" aria-hidden="true" title="user"></span></div></div>
      <div class="col-md-4 col-xs-4" data-toggle="popover" data-placement="right" data-content="<%= render partial: 'users/user_popover', locals: { user: project.user} %>" data-trigger="hover" data-html="true"><%= project.user.email %></div>
      <div class="col-md-1 col-md-offset-1 col-xs-1"><%= link_to '', edit_user_project_path(project.user, project), class: 'glyphicon glyphicon-wrench', 'aria-hidden' => true, 'title' => 'rename' %></div>
      <div class="col-md-1 col-xs-1"><%= link_to '', project, class: 'destroy_project glyphicon glyphicon-trash', method: :delete, remote: true, 'aria-hidden' => true, 'title' => 'delete project' %></div>
      <!-- delete_project_path(project.user, project) -->
      <div class="col-md-1 col-xs-1"><%= link_to '', '#', class: 'add_task glyphicon glyphicon-plus pr#{project.id}', 'aria-hidden' => true, 'title' => 'new task', 'name' => "pr#{project.id}" %></div>
      <!-- new_project_task_path(project) -->
    </div>
  </li>
  <li class="list-group-item">
    <ul class="list-group sortable list">
      <% if project.tasks %>
        <% project.tasks.each do |task| %>
          <div class="task_each_div">
            <%= render  partial: "tasks/task", locals: { task: task, project: project } %>
            <% if current_user || (task.user == current_user) %>
              <%= render  partial: "tasks/ed_form", locals: { task: task, project: project, 'draggable' => false } %>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <% if current_user %>
        <% if current_user == project.user %>
          <%= render partial: 'tasks/form', locals: { task: @task, project: project, 'draggable' => false } %>
        <% else %>
          <%= render 'tasks/create_task_error', :project => project, 'draggable' => false %>
        <% end %>
      <% else %>
        <%= render 'tasks/create_task_error', :project => project, 'draggable' => false %>
      <% end %>
    </ul>
  </li>
</ul>

app/views/projects/create.js.erb
$('.projects').append("<%= j(render partial: 'project', locals: { project: @project, task: @project.tasks }) %>");

app/views/projects/destroy.js.erb
$('ul.list-group.pr<%= @project.id %>').hide(1000)

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<div>  
  <%= form_with(model: @project, local: true) do |form| %>
    <% if @project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :project_name, required: true %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

<%= link_to 'Show', user_project_path(@project.user, @project) %> |
<%= link_to 'Back', root_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>user_id</th>
      <th>created_at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %> Project</td>
        <td><%= project.user_id %></td>
        <td><%= project.created_at %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Create Task', new_project_task_path(project) %></td>
      </tr>
      <tr>
        <% project.tasks.each do |task| %>
          <td><%= task.id %> Task</td>
          <td><%= task.name %></td>
          <td><%= task.priority %></td>
          <td><%= task.deadline %></td>
          <td><%= link_to 'Show', project_task_path(project, task) %></td>
          <td><%= link_to 'Edit', edit_project_task_path(project, task) %></td>
          <td><%= link_to 'Destroy', delete_comment_path(project, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_user_project_path(current_user) %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_user_project_path(@project.user, @project) %> |
<%= link_to 'Back', root_path %>